#!/usr/bin/env bash
# Build a CRX/zip-style artifact for upload to Chrome Web Store / Firefox AMO.
# Output lands in dist/. The dist/ dir is gitignored.

set -euo pipefail

cd "$(dirname "$0")/.."

# Sentry SDK vendoring (QM-169) — only when SENTRY_DSN is set in the env.
# Releasers export SENTRY_DSN before running `npm run package`; dev builds
# leave it unset and the vendored bundle is omitted, which the runtime
# tolerates (sentry-init.js no-ops when globalThis.Sentry is missing).
if [ -n "${SENTRY_DSN:-}" ]; then
  echo "→ SENTRY_DSN detected; vendoring @sentry/browser…"
  bash scripts/vendor-sentry.sh

  # Inject the DSN as a self-bound global before sentry-init.js reads it.
  # We write a small lib/sentry-dsn.js shim so the value never lands in
  # the source tree on disk (it's regenerated each build, gitignored,
  # and stripped from dev builds).
  RELEASE_VERSION=$(node -e "console.log(require('./package.json').version)")
  SENTRY_ENV_VALUE="${QM_SENTRY_ENV:-production}"
  # JSON.stringify each value so any quote/backslash in DSN is safely escaped.
  RELEASE_VERSION="$RELEASE_VERSION" SENTRY_ENV_VALUE="$SENTRY_ENV_VALUE" SENTRY_DSN="$SENTRY_DSN" node -e '
    const fs = require("fs");
    const out = [
      "/* Generated by scripts/package.sh. Do not edit. Gitignored. */",
      "self.QM_SENTRY_DSN = " + JSON.stringify(process.env.SENTRY_DSN) + ";",
      "self.QM_SENTRY_RELEASE = " + JSON.stringify(process.env.RELEASE_VERSION) + ";",
      "self.QM_SENTRY_ENV = " + JSON.stringify(process.env.SENTRY_ENV_VALUE) + ";",
      ""
    ].join("\n");
    fs.writeFileSync("lib/sentry-dsn.js", out);
  '
  echo "✓ wrote lib/sentry-dsn.js (release ${RELEASE_VERSION}, env ${SENTRY_ENV_VALUE})"
else
  echo "→ SENTRY_DSN not set; skipping Sentry vendoring (dev build)"
  # Drop both the DSN shim AND the vendored bundle. Otherwise a previous
  # production build leaves lib/vendor/sentry.min.js on disk and web-ext
  # bundles it into the next zip, which means a "Sentry-less" build
  # actually still ships the vendored SDK and AMO will demand source.
  rm -f lib/sentry-dsn.js lib/vendor/sentry.min.js
fi

mkdir -p dist
echo "→ building extension zip with web-ext…"
npx --yes web-ext@8 build \
  --source-dir . \
  --artifacts-dir dist/ \
  --overwrite-dest \
  --ignore-files \
    "node_modules/**" \
    "test/**" \
    "scripts/**" \
    "plans/**" \
    "docs/**" \
    "worktrees/**" \
    ".worktrees/**" \
    "coverage/**" \
    "playwright-report/**" \
    "test-results/**" \
    ".playwright-user-data/**" \
    "*.md" \
    "*.log" \
    ".github/**" \
    ".claude/**" \
    ".memsearch/**" \
    "package*.json" \
    "vitest.config.*" \
    "playwright.config.*" \
    ".gitignore" \
    "dist/**"

echo "→ stripping any *.map files from artifact (defensive — repo currently produces none)"
for zip in dist/*.zip; do
  [ -f "$zip" ] || continue
  if zipinfo -1 "$zip" 2>/dev/null | grep -q '\.map$'; then
    zip -d "$zip" '*.map' >/dev/null
    echo "  removed source maps from $(basename "$zip")"
  fi
done

echo "→ artifact:"
ls -lh dist/*.zip 2>/dev/null || { echo "(no zip produced)"; exit 1; }
